import React, { Component } from 'react';
import { Heading } from './lib';

class App extends Component {
  render() {
    return (
      <div>
        <Heading level="1">h1. Megan heading</Heading>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis nec erat vitae mauris congue ornare et ut ex. Morbi at porttitor turpis, sit amet dictum elit. Praesent quis sodales leo. Sed leo ante, cursus nec aliquet in, venenatis ac lectus. Maecenas tincidunt non orci sit amet luctus. Praesent eu volutpat quam, eu egestas quam. Fusce finibus libero id nisl condimentum placerat. Etiam quis purus non enim ornare ultrices non quis mauris. Morbi at nibh vitae justo hendrerit condimentum ut quis elit. Sed rutrum lectus in nisl viverra euismod. Nulla facilisis elementum enim. Aliquam sagittis sem eget sem hendrerit, non egestas nisl pellentesque. Sed ultrices pellentesque molestie. Nulla dolor mauris, commodo eu scelerisque vitae, aliquet et quam.</p>
        <Heading level="2">h2. Megan heading</Heading>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis nec erat vitae mauris congue ornare et ut ex. Morbi at porttitor turpis, sit amet dictum elit. Praesent quis sodales leo. Sed leo ante, cursus nec aliquet in, venenatis ac lectus. Maecenas tincidunt non orci sit amet luctus. Praesent eu volutpat quam, eu egestas quam. Fusce finibus libero id nisl condimentum placerat. Etiam quis purus non enim ornare ultrices non quis mauris. Morbi at nibh vitae justo hendrerit condimentum ut quis elit. Sed rutrum lectus in nisl viverra euismod. Nulla facilisis elementum enim. Aliquam sagittis sem eget sem hendrerit, non egestas nisl pellentesque. Sed ultrices pellentesque molestie. Nulla dolor mauris, commodo eu scelerisque vitae, aliquet et quam.</p>      
        <Heading level="3">h3. Megan heading</Heading>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis nec erat vitae mauris congue ornare et ut ex. Morbi at porttitor turpis, sit amet dictum elit. Praesent quis sodales leo. Sed leo ante, cursus nec aliquet in, venenatis ac lectus. Maecenas tincidunt non orci sit amet luctus. Praesent eu volutpat quam, eu egestas quam. Fusce finibus libero id nisl condimentum placerat. Etiam quis purus non enim ornare ultrices non quis mauris. Morbi at nibh vitae justo hendrerit condimentum ut quis elit. Sed rutrum lectus in nisl viverra euismod. Nulla facilisis elementum enim. Aliquam sagittis sem eget sem hendrerit, non egestas nisl pellentesque. Sed ultrices pellentesque molestie. Nulla dolor mauris, commodo eu scelerisque vitae, aliquet et quam.</p>
        <Heading level="4">h4. Megan heading</Heading>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis nec erat vitae mauris congue ornare et ut ex. Morbi at porttitor turpis, sit amet dictum elit. Praesent quis sodales leo. Sed leo ante, cursus nec aliquet in, venenatis ac lectus. Maecenas tincidunt non orci sit amet luctus. Praesent eu volutpat quam, eu egestas quam. Fusce finibus libero id nisl condimentum placerat. Etiam quis purus non enim ornare ultrices non quis mauris. Morbi at nibh vitae justo hendrerit condimentum ut quis elit. Sed rutrum lectus in nisl viverra euismod. Nulla facilisis elementum enim. Aliquam sagittis sem eget sem hendrerit, non egestas nisl pellentesque. Sed ultrices pellentesque molestie. Nulla dolor mauris, commodo eu scelerisque vitae, aliquet et quam.</p>
        <Heading level="5">h5. Megan heading</Heading>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis nec erat vitae mauris congue ornare et ut ex. Morbi at porttitor turpis, sit amet dictum elit. Praesent quis sodales leo. Sed leo ante, cursus nec aliquet in, venenatis ac lectus. Maecenas tincidunt non orci sit amet luctus. Praesent eu volutpat quam, eu egestas quam. Fusce finibus libero id nisl condimentum placerat. Etiam quis purus non enim ornare ultrices non quis mauris. Morbi at nibh vitae justo hendrerit condimentum ut quis elit. Sed rutrum lectus in nisl viverra euismod. Nulla facilisis elementum enim. Aliquam sagittis sem eget sem hendrerit, non egestas nisl pellentesque. Sed ultrices pellentesque molestie. Nulla dolor mauris, commodo eu scelerisque vitae, aliquet et quam.</p>
        <Heading level="6">h6. Megan heading</Heading>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis nec erat vitae mauris congue ornare et ut ex. Morbi at porttitor turpis, sit amet dictum elit. Praesent quis sodales leo. Sed leo ante, cursus nec aliquet in, venenatis ac lectus. Maecenas tincidunt non orci sit amet luctus. Praesent eu volutpat quam, eu egestas quam. Fusce finibus libero id nisl condimentum placerat. Etiam quis purus non enim ornare ultrices non quis mauris. Morbi at nibh vitae justo hendrerit condimentum ut quis elit. Sed rutrum lectus in nisl viverra euismod. Nulla facilisis elementum enim. Aliquam sagittis sem eget sem hendrerit, non egestas nisl pellentesque. Sed ultrices pellentesque molestie. Nulla dolor mauris, commodo eu scelerisque vitae, aliquet et quam.</p>
      </div>
    );
  }
}

export default App;
